=== Data4Democracy/boston-crash-modeling/data_standards/crashes-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Crashes",
    "description": "Defines the structure of a set of crashes",
    "type": "array",
    "items": {
        "title": "Crash",
        "description": "Defines the structure of a crash",
        "type": "object",
        "properties": {
            "id": {
                "description": "Unique identifier of crash",
                "type": "number"
            },
            "dateOccurred": {
                "description": "Date crash occurred, ISO8601 formatted",
                "type": "string",
                "format": "date-time"
            },
            "type": {
                "description": "Type of crash",
                "type": "string",
                "enum": ["car", "bike", "pedestrian", "other"]
            },
            "location": {
                "description": "Coordinates of crash, WGS84 formatted",
                "type": "object",
                "properties": {
                    "latitude": {
                        "description": "Latitude of crash",
                        "type": "number"
                    },
                    "longitude": {
                        "description": "Longitude of crash",
                        "type": "number"
                    }
                }
            },
            "address": {
                "description": "Address of crash",
                "type": "string"
            },
            "summary": {
                "description": "Summary of crash",
                "type": "string"
            }
        },
        "required": ["id", "dateOccurred", "type", "location"]
    }
}

=== Data4Democracy/boston-crash-modeling/data_standards/crashes-instance.json
[
    {
        "id": 1403832,
        "dateOccurred": "2016-01-01T00:56:45-05:00",
        "type": "car",
        "location": {
            "latitude": 42.300864811284519,
            "longitude": -71.071316786983303
        },
        "address": "14 Corona Street",
        "summary": "REPORTED INJURIES (P) (E) (F)"
    },
    {
        "id": 1410434,
        "dateOccurred": "2016-01-04T15:11:11-05:00",
        "type": "pedestrian",
        "location": {
            "latitude": 42.332547160943271,
            "longitude": -71.072124196868316
        },
        "summary": "PEDESTRIAN STRUCK (P) (E) (F)"
    },
    {
        "id": 1410816,
        "dateOccurred": "2016-01-04T18:42:24-05:00",
        "type": "car",
        "location": {
            "latitude": 42.311376108568268,
            "longitude": -71.081614220307372
        },
        "address": "67 Brunswick Street, Boston",
        "summary": "UNKNOWN IF INJURIES - ADVISE NEED FOR EMS (P) (E) (F)"
    }
]
